### PR TITLE
Fix bower package version to be semantic.

### PR DESCRIPTION
**Pull request by patrickberkeley**

### CODE REVIEW

**Comment by catc** [comment]
Can you update it to v2.1.0 and then I'll merge.

**Comment by patrickberkeley** [comment]
Yup, updated

**Comment by patrickberkeley** [comment]
@catc anyway you could publish this to the bower registry? I'm not seeing it there: http://bower.io/search/?q=simple-hint

**Comment by catc** [comment]
Yeah, I'll add it now.

**Comment by patrickberkeley** [comment]
:+1: thanks!

**Pull request merged**
